### PR TITLE
[INFRA-3943] Run `go get -u ./...` followed by `go mod vendor`

### PR DESCRIPTION
**Pull request by zombar**

### CODE REVIEW

**Review by sazap10 — DISMISSED** [review]
As long as it builds ok. I'm surprised we dont have a buildkite pipeline with basic docker build and linting for this

**Comment by zombar** [comment]
Font handling has completely changed in the latest version of gonum, apparently the use of `MakeFont` was a workaround for some earlier bug. Now we are required to ship with our own fonts and build a font cache, we can then pluck the fonts from the cache as we need them.

I pinched the Ubuntu font for this as it's fairly close to Helvetica (it's a serif font at least), this app has gone through some reworking so I'll need to do some additional testing before I'm happy.

**Comment by zombar** [comment]
This is helpful to know btw because it's not clear, but flux-alerting includes a local Promalert which is useful for testing: https://github.com/bugsnag/flux-alerting/blob/main/docker-compose.dev.yml#L69

**Comment by zombar** [comment]
> This is helpful to know btw because it's not clear, but flux-alerting includes a local Promalert which is useful for testing: https://github.com/bugsnag/flux-alerting/blob/main/docker-compose.dev.yml#L69

Actually, I think I'll create a local test stack for Promalert. There's no Prometheus in this one - should be quick

**Pull request closed without merging**
