### PR TITLE
[INFRA-3590] Don't shorten specifically excluded annotations

### PR DESCRIPTION
**Pull request by zombar**
Rather than mess about trying to detect links we shouldn't shorten, we instead present a de facto list to the app.

This is presented as an alternative to #29

### CODE REVIEW

**Comment by trvrnrth** [comment]
I'm not sure I follow how this would be used? If we have descriptions/summaries which may contain both long breakdown links and code-formatted endpoint URLs how would this be configured?

**Comment by trvrnrth** [comment]
Can we not do what I suggested in #30?

Something like this:
```
func (cli *Client) ReplaceLinks(ctx context.Context, target string) (error, string) {
	r := regexp.MustCompile("([^`]|^)(" + xurls.Strict().String() + ")([^`]|$)")
	r.Longest()

	raw := r.FindAllStringSubmatch(target, -1)
	for _, r := range raw {
		url, err := cli.Submit(ctx, r)
		if err != nil {
			return err, r
		}
		clog.Infof("Shortened link: %s, to: %s", url.Target, url.Link)
		target = strings.Replace(target, r[1], url, 1)
	}
}
```

**Comment by trvrnrth** [comment]
Another option would be to keep the regex as-is, use FindAllStringIndex and do a manual negative lookaround.

**Comment by zombar** [comment]
> I'm not sure I follow how this would be used? If we have descriptions/summaries which may contain both long breakdown links and code-formatted endpoint URLs how would this be configured?

Ah I rushed it and got a little bit confused, really we want to be treating the labels not the annotations.

As for the rest of it, which part isn't clear? The URLs come in via the labels, we exclude those labels from processing so they appear in the alert as intended.

**Comment by zombar** [comment]
> Can we not do what I suggested in #30?
> 
> Something like this:
> 
> ```
> func (cli *Client) ReplaceLinks(ctx context.Context, target string) (error, string) {
> 	r := regexp.MustCompile("([^`]|^)(" + xurls.Strict().String() + ")([^`]|$)")
> 	r.Longest()
> 
> 	raw := r.FindAllStringSubmatch(target, -1)
> 	for _, r := range raw {
> 		url, err := cli.Submit(ctx, r)
> 		if err != nil {
> 			return err, r
> 		}
> 		clog.Infof("Shortened link: %s, to: %s", url.Target, url.Link)
> 		target = strings.Replace(target, r[1], url, 1)
> 	}
> }
> ```

I find it a bit strange that you think this is a good idea. Isn't it clearly better to simply exclude the labels we don't want to process? Why are you married to this solution?

**Comment by trvrnrth** [comment]
> > I'm not sure I follow how this would be used? If we have descriptions/summaries which may contain both long breakdown links and code-formatted endpoint URLs how would this be configured?
> 
> Ah I rushed it and got a little bit confused, really we want to be treating the labels not the annotations.
> 
> As for the rest of it, which part isn't clear? The URLs come in via the labels, we exclude those labels from processing so they appear in the alert as intended.

If we have an alert with a summary/description of ```Endpoint `http://endpoint.com` is not working. See <http://reallylonglinktobreakdown|breakdown>``` (which is basically what we have at present across multiple alerts) how will your proposed solution work?

**Comment by zombar** [comment]
Not the answer.

**Pull request closed without merging**
